# Generated by Django 4.2.30 on 2026-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
